image: node:10

pipelines:
  branches:
    master:
      - step:
          script:
            # Install module dependencies
            - npm ci
            - npm run lint
            - npm run secure
            # Build
            - npm run build

            # Run unit tests
            - npm run test:cover
            - npm run codecov

            # Publish package
            - npm publish --access=public

    feature/*:
      - step:
          script:
            # Install module dependencies
            - npm ci
            - npm run lint
            - npm run secure

            # Build
            - npm run build

            # Run unit tests
            - npm run test:cover
            - npm run codecov
